#!/bin/sh
#export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib

cat << EOF | sqlplus64 "username/password@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle.scs.ryerson.ca)(Port=1521))(CONNECT_DATA=(SID=orcl)))"

DROP TABLE PATIENT CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;
DROP TABLE DOCTORS CASCADE CONSTRAINTS;
DROP TABLE RECEPTIONISTS CASCADE CONSTRAINTS;
DROP TABLE NURSES CASCADE CONSTRAINTS;
DROP TABLE RECORDS CASCADE CONSTRAINTS;
DROP TABLE ROOMS CASCADE CONSTRAINTS;
DROP TABLE TEST_PRICE CASCADE CONSTRAINTS;
DROP TABLE LABS CASCADE CONSTRAINTS;
DROP TABLE BILLS CASCADE CONSTRAINTS;

--DROP VIEW NUMBER_OF_NURSES_IN_EACH_ROOM;
--DROP VIEW UPCOMING_APPOINTMENTS;

EOF

exit; 


